name: Product
description: Project level product
parents:
  - BaseProduct
level: ALL
schema: '1.1'
metadata:
    type:
        current_id: type
        id: type
        id_zh_cn: 产品类型
        fits_keyword: TYPE
        data_type: string
        description: Product Type identification. Fully qualified Python class name
            or CARD.
        description_zh_cn: 产品类型。完整Python类名或卡片名。
        examples: SAT-QM-ThermVac
        default: Product
        valid: ''
        valid_zh_cn: ''
        typecode: B
    startDate:
        current_id: startDate
        id: startTime
        id_zh_cn: 产品的标称起始时间
        fits_keyword: DATE_OBS
        data_type: finetime
        description: Nominal start time  of this product.
        description_zh_cn: 产品标称的起始时间
        examples: '10361455509632'
        default: 0
        valid: ''
        valid_zh_cn: ''
        typecode:
    endDate:
        current_id: endDate
        id: endTime
        id_zh_cn: 产品的标称结束时间
        fits_keyword: DATE_END
        data_type: finetime
        description: Nominal end time  of this product.
        description_zh_cn: 产品标称的结束时间
        examples: '10361455509632'
        default: 0
        valid: ''
        valid_zh_cn: ''
        typecode:
    instrument:
        current_id: instrument
        id: instrument
        id_zh_cn: 观测仪器名称
        fits_keyword: INSTRUME
        data_type: string
        description: Instrument that generated data of this product
        description_zh_cn: 观测仪器名称
        examples: VT
        default: UNKOWN
        valid: ''
        valid_zh_cn: ''
        typecode: B
    modelName:
        current_id: modelName
        id: modelName
        id_zh_cn: 样机名称
        fits_keyword: MODEL
        data_type: string
        description: Model name of the instrument of this product
        description_zh_cn: 观测仪器样机名称
        examples: QM
        default: UNKOWN
        valid: ''
        valid_zh_cn: ''
        typecode: B
    mission:
        current_id: mission
        id: mission
        id_zh_cn: 任务名称
        fits_keyword: TELESCOP
        data_type: string
        description: Name of the mission.
        description_zh_cn: 任务名称
        examples: SVOM
        default: _AGS
        valid: ''
        valid_zh_cn: ''
        typecode: B
    version:
        current_id: formatVersion
        id: version
        id_zh_cn: 格式版本
        fits_keyword: VERSION
        data_type: string
        description: Version of product schema
        description_zh_cn: 产品格式版本
        examples: '1'
        default: '0.6'
        valid: ''
        valid_zh_cn: ''
        typecode: B
